baseurl = "/"
languageCode = "en-us"
theme = "hello-friend"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "post"

  # OS theme is default when not provided, but you can force it to "light" or "dark"
  defaultTheme = "dark"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 4

  # Show reading time in minutes for posts
  showReadingTime = false

  # Show table of contents at the top of your posts (defaults to false)
  # Alternatively, add this param to post front matter for specific posts
  # toc = true

  # Show full page content in RSS feed items
  #(default is Description or Summary metadata in the front matter)
  rssFullText = true

[languages]
  [languages.en]
    title = "Ahmad Site"
    subtitle = "Simple web for learning."
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = "by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "New posts"
    olderPosts = "Old posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "Jan 2, 2006"
    dateFormatList = "Jan 2, 2006"
    # leave empty to disable, enter display text to enable
    # lastModDisplay = ""

    [languages.en.params.logo]
      logoText = "Ahmad Site"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "/about"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "tags"
        name = "/tags"
        url = "/tags"
      [[languages.en.menu.main]]
        identifier = "project"
        name = "/project"
        url = "/project"